### PR TITLE
add select function to ide

### PR DESCRIPTION
**Pull request by dokechin**
Selenium IDE Perl Webdriver has added select function.
But not soficicated code, sorry.

### CODE REVIEW

**Comment by gempesaw** [comment]
How is `select` called, what is `selectLocator`, I guess it's something that comes from the webdriver side and has a `.string` property ?

**Comment by dokechin** [comment]
When selectbox is selected, the select function will called.

Rpec Formatter has select function.so I imitated that implementation for perl.
https://github.com/SeleniumHQ/selenium/blob/master/ide/plugins/ruby-format/src/content/formats/ruby-wd-rspec.js

**Comment by gempesaw** [comment]
Oh! Thanks for that link, that's very helpful. I'm a bit reluctant about hardcoding the use of `xpath` and doing a text search on the select children. I think it'd be nice to be more flexible to support more ways of doing the selection.

**Comment by gempesaw** [comment]
Thanks again - looking back at the [very helpful ruby example](https://github.com/SeleniumHQ/selenium/blob/master/ide/plugins/ruby-format/src/content/formats/ruby-wd-rspec.js#L504), it looks like we probably want to support a few different values for `selectLocator.type`: `index`, `value`, and as a fall back, the text version that you've already provided. Let me know if you're interested in extending this code, otherwise I don't think I'll be merging this right now. Thanks!

**Comment by gempesaw** [comment]
replaced by #273

**Pull request closed without merging**
