### PR TITLE
Fix issues with paths containing .. in upload path (see PR 194)

### PR DESCRIPTION
**Pull request by teodesian**
It was reported that paths passed to upload_file would have difficulty when they contained .. as a component.  Apparently 'zip' would pass this as multiple files to the server.

Canonicalizing the path passed to _prepare_file and adding more severe warnings when passing raw data seem a prudent way to avoid this issue.

I also took the liberty of adding unit tests to walk the path where 'zip' and encode_base64 are called to maximize coverage.

### CODE REVIEW

**Comment by teodesian** [comment]
huh, guess it didn't like the mock recording.

oh, yeah.  atime will mean a different encoded blob every time it's run anywhere.  I have just the thing.

**Comment by teodesian** [comment]
hmm, will have to test with custom Test::LWP::UA.  even straight up cheating with overriding the recording store doesn't work right (yikes!)  so, gotta break out the elephant gun.

**Comment by gempesaw** [comment]
excellent, I was vaguely thinking about using `abs_path` but I had no idea about the 1-file limitation, or `zip`'s weird behavior. and, you suggested it _and_ implemented it before I had a chance. hooray!

**Comment by teodesian** [comment]
I'll probably have a more acceptable mocking solution ready sometime this afternoon.

**Comment by gempesaw** [comment]
thanks!

**Comment by jamadam** [comment]
Hmm. Actually this commit didn't solve my problem #194 due to server side bug workaround.
I found a workaround for this. t/01-driver.t test passes but not sure the implementation is appropriate.

https://github.com/jamadam/Selenium-Remote-Driver/commit/ce7048027a52cdace682b39ed9906f2e12f89047

**Comment by jamadam** [comment]
Yet another workaround.

https://github.com/jamadam/Selenium-Remote-Driver/commit/a8c0da820807c7556ed5f5603f7ee96ebe8b4038

**Comment by gempesaw** [comment]
(like last time, I'll defer to @teodesian if they're up to it, but I'll also take a look at some point this week :) )

**Comment by teodesian** [comment]
Have made a couple of comments on @jamadam 's later commit (03b5aa1).  As far as I can tell, zip() still has trouble with absolute paths too?  I'm guessing the only safe way to use it for @jamadam's particular use case is to be in the directory of the file to upload and then pass it's basename.  Or, to build a relative path that has no .. in it ( if passed relpath {get abs path, get cwd, remove cwd from abs path}, etc...)

This makes me really curious about the use case that is causing this trouble.  This almost feels like a windows problem I had with another one of my distributions.

**Comment by teodesian** [comment]
My analysis above is faulty, disregard.

Based on my understanding of the IO::Compress::Zip module, this would set the zipfile 'Name' header to the basename of the file.  This is probably the proximate cause of @jamadam's issue.

**Comment by jamadam** [comment]
My solution may not be appropriate but the issue is oviously and reproducable. And It's no longer .. issue.

With this case

    like( $fake_driver->upload_file('t/uploadTest'),qr/uploadTest$/,'upload_file: zip/base64 branch' );

The abs path will be sent to server.

    /Users/sugamakeita/Documents/dev/Selenium-Remote-Driver/t/uploadTest

On server side, this file will be created. Temp directory + local full path.

    /var/folders/xf/mwgy81ys54j69pswy6ld5hyc0000gn/T/bfce6c93-9a68-4fd9-a1a5-d26cfc2fe4a6/upload3963139111656408215file/Users/sugamakeita/Documents/dev/Selenium-Remote-Driver/t/uploadTest

Retrun value from server is broken.

    /var/folders/xf/mwgy81ys54j69pswy6ld5hyc0000gn/T/bfce6c93-9a68-4fd9-a1a5-d26cfc2fe4a6/upload3963139111656408215file/Users

With existing workarround, last value will be like this. And it's wrong.

    /var/folders/xf/mwgy81ys54j69pswy6ld5hyc0000gn/T/bfce6c93-9a68-4fd9-a1a5-d26cfc2fe4a6/upload3963139111656408215file/t/uploadTest

It happens on mac and centos6.5.

My 1st commit simply fix this. Please forget about 2nd one.

**Comment by teodesian** [comment]
Ok, so looking at your first commit, it seems the problem would be a bit simpler stated as

"Now that we're always passing the abs_path to the zipped file, the bug which must be worked around (abs_paths & files not in CWD makes the server not return the full path to the file uploaded) will be triggered on every upload.  However, we are not updating this filename now due to my previous PR not returning the altered filename uploaded."

As such, jamadam@ce70480 *should* be a good fix.  The unit tests seem like they should do the trick catching this correctly as well.  So I say do a PR.  That commit looks good.

The only question in my mind is what this would do supposing selenium 'all the sudden' fixed this odd behavior in some future release.  I think changing the check to do the workaround with catpath to be ($file ne basename($filename)) would end up being more robust in that regard, and shouldn't impact this fix.  @jamadam, I'll send a PR doing that -- let me know if it works for you.

**Comment by teodesian** [comment]
Ok, I've made a PR to your upload_file_improve2 branch.  Let me know how it works out.

**Comment by teodesian** [comment]
You know, it's worth thinking about the whole 'Name' header in zip a bit more.

Might it be that this odd edge case we're working around be caused in the first place by not setting this?  If that's so, the third commit you made (jamadam@03b5aa1) might be on to something.  I'll send a PR to that branch completely removing the workaround bits and I want to see if the unit tests still pass on a real selenium remote driver (the first 2 tests in the upload_file section of driver.t)

If those tests do pass, I suspect this line of reasoning might just be the most elegant solution of all.

**Comment by jamadam** [comment]
Thanks for PR and rewriting the comment :)
I admin your suggestion is safer.

**Comment by jamadam** [comment]
Better turn down the PR?

**Comment by teodesian** [comment]
No, let's see whether the theory about the zip headers pans out first.  Pretty sure the first one should work, even if it's a bit uglier.

**Comment by jamadam** [comment]
OK. Thanks.

Talking about zip headers, I tested with real use case and worked fine on some environments.
However I'm just curious that the Name header seems to be accepted just one, where multiple files are accepted.

**Comment by teodesian** [comment]
Have made a PR to the upload_file_improve3 branch on your fork:
https://github.com/jamadam/Selenium-Remote-Driver/pull/2

If you pass multiple files, selenium will probably do something strange; remember that it would explode saying it didn't want multiple files when we tried to use .. in the path earlier.

Might be worth noting in the POD to 'not upload multiple files' in a zip stream...but you should only be able to do that by passing raw data, and you probably deserve whatever happens from that point (I only added that feature for testability anyways).

**Comment by jamadam** [comment]
Yes, in our case, we don't have to worry about multiple files.
I talking about zip specification itself for right understanding of Name header option.

According to wikipedia :), zip can contains multiple files and corresponding multiple headers. But IO::Compress::Zip seems to take just one. I'm also studying Archive::Zip which I::C::Zip pod suggests for general-purpose usage.

Thanks for PR. I'll check it.

**Comment by teodesian** [comment]
Yeah, I had the sneaking suspicion that a better zip backend might be worth considering.  Thanks for looking at this stuff further.

**Comment by gempesaw** [comment]
fwiw: we're already using Archive::Zip for Selenium::Firefox::Profile, so it wouldn't be an additional dependency :)

**Comment by jamadam** [comment]
Thanks you two.

IO::Compress::Zip looks ok for our case. Following code generates a zip including two foo.txt in same directory!

    zip ['./foo.txt', './bar.txt'] => './out.zip', Name => 'foo.txt';

Archive::Zip looks more straightforward to specify name header for a file.
However I haven't found a way to get binary instead of file.

    use Archive::Zip;
    my $zip = Archive::Zip->new();
    $zip->addFile('t/../t/uploadTest', 'uploadTest');
    $zip->writeToFileNamed('out.zip');

**Comment by gempesaw** [comment]
I think there's a function that just writes to a file handle instead of a file name. perhaps https://github.com/gempesaw/Selenium-Remote-Driver/blob/01787faacc1e3d327c712309095685792a33992b/lib/Selenium/Firefox/Profile.pm#L225

**Comment by jamadam** [comment]
Thanks. I've just found a solution.

    $zip->writeToFileHandle(IO::String->new($string))

**Comment by jamadam** [comment]
Made a PR. mock-recording is not updated. Don't I missing anything?

**Comment by jamadam** [comment]
@gempesaw @teodesian 

This is continuation of the discussion at below comment.

https://github.com/jamadam/Selenium-Remote-Driver/commit/03b5aa11b93e00e25894a3351af9f7c24d51f29b#commitcomment-10932285

I sent two PRs, 
https://github.com/gempesaw/Selenium-Remote-Driver/pull/199 and https://github.com/gempesaw/Selenium-Remote-Driver/pull/200. Either of them should be applied, but not both.

I prefer https://github.com/gempesaw/Selenium-Remote-Driver/pull/200 but would like both of you review it.

**Comment by jamadam** [comment]
@gempesaw @teodesian 

I've tested both patches and believe both is merge ready.One thing, @teodesian mentioned that the POD should be fixed if we choose #199. I think current pod is OK but will double check later.

https://github.com/jamadam/Selenium-Remote-Driver/pull/2#issuecomment-95778250

"Oh, and if we decide to go with upload_file_improve2 over this branch, be sure to cherry-pick the warning commit above into that branch (it still applies)."

**Comment by jamadam** [comment]
Hmm. I think I better turn down #199. 

#200 is more elegant where $filename isn't required when $raw_content is given, not documented, though.

**Pull request merged**
